version: '3.8'

services:
  app:
    build: .
    container_name: lendingfront_app
    ports:
      - "5000:5000"
    env_file:
      - .env 
    volumes:
      - .:/app
    networks:
      - lendingfront_network

networks:
  lendingfront_network:
    driver: bridge
